# I'm putting this crate in this repo for now but its final home should be in the open source repo as part of the halo2 frontent crate.

[package]
name = "llzk-halo2-support"
version = "0.1.0"
edition = "2024"

[dependencies]
midnight-proofs = { path = "../proofs" }


